name: library_management
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"  # Ensure Dart SDK compatibility
  flutter: ">=3.0.0 <4.0.0"  # Match Flutter SDK version range

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0  # Updated firebase_core to the latest
  firebase_auth: ^5.3.2  # Updated firebase_auth to the latest
  cloud_firestore: ^5.4.5  # Updated cloud_firestore to the latest
  provider: ^6.1.2
  google_generative_ai: ^0.4.0
  intl: ^0.17.0                    # Add intl package for date formatting
  flutter_email_sender: ^5.0.0
  cloud_functions: ^5.1.4
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  # Updated to latest version

flutter:
  uses-material-design: true
